# Qt 6 Base Module for HobbyCAD static builds
# Source: PPA dfsg tarball (hosted on GitHub releases)

set(QT_VERSION 6.4.2)

vcpkg_download_distfile(ARCHIVE
    URLS
        "https://github.com/ayourk/hobbycad-vcpkg/releases/download/sources/qt6-base_${QT_VERSION}+dfsg.orig.tar.xz"
    FILENAME "qt6-base_${QT_VERSION}+dfsg.orig.tar.xz"
    SHA512 2704b90dab05ad2bc31a1171e2818aaa694d5d579d0defe27f9806f3d6c6263467c0673415b3fa73612e45f076442b5fe003d79b9eb758489616263153189a8d
)

vcpkg_extract_source_archive(
    SOURCE_PATH
    ARCHIVE "${ARCHIVE}"
    SOURCE_BASE "qtbase-everywhere-src-${QT_VERSION}"
    PATCHES
        fix-macos-visibility-test.patch
        add-wintab-headers.patch
        fix-threads-global-promotion.patch
        fix-qduplicatetracker-include.patch
)

vcpkg_find_acquire_program(PERL)
get_filename_component(PERL_PATH ${PERL} DIRECTORY)
vcpkg_add_to_path(${PERL_PATH})

vcpkg_find_acquire_program(PYTHON3)
get_filename_component(PYTHON3_PATH ${PYTHON3} DIRECTORY)
vcpkg_add_to_path(${PYTHON3_PATH})

# Feature options for HobbyCAD's needs
set(FEATURE_OPTIONS
    -DFEATURE_concurrent=ON
    -DFEATURE_dbus=OFF
    -DFEATURE_gui=ON
    -DFEATURE_network=OFF
    -DFEATURE_opengl=ON
    -DFEATURE_printsupport=OFF
    -DFEATURE_sql=OFF
    -DFEATURE_testlib=OFF
    -DFEATURE_widgets=ON
    -DFEATURE_xml=ON
)

# Dependency configuration
set(INPUT_OPTIONS
    -DINPUT_doubleconversion=system
    -DINPUT_freetype=system
    -DINPUT_harfbuzz=system
    -DINPUT_libjpeg=system
    -DINPUT_libpng=system
    -DINPUT_pcre=system
)

# Platform-specific options
set(PLATFORM_OPTIONS "")
if(VCPKG_TARGET_IS_WINDOWS)
    list(APPEND PLATFORM_OPTIONS
        -DFEATURE_opengl_desktop=ON
    )
elseif(VCPKG_TARGET_IS_OSX)
    list(APPEND PLATFORM_OPTIONS
        -DFEATURE_opengl_desktop=ON
        -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
    )
endif()

# Disable features not needed
set(DISABLE_OPTIONS
    -DCMAKE_DISABLE_FIND_PACKAGE_ATSPI2=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Cups=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_DirectFB=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_EGL=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Fontconfig=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_GLESv2=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_GLIB2=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_GSSAPI=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_GTK3=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Libdrm=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Libinput=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Libproxy=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_LTTngUST=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Mtdev=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_MySQL=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_ODBC=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Oracle=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_PostgreSQL=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_SQLite3=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Slog2=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Tslib=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_Vulkan=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_WrapBrotli=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_WrapDBus1=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_WrapOpenSSL=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_X11=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_XCB=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_XKB=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_ZSTD=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_gbm=ON
    -DCMAKE_DISABLE_FIND_PACKAGE_libb2=ON
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DBUILD_SHARED_LIBS=OFF
        -DQT_BUILD_EXAMPLES=OFF
        -DQT_BUILD_TESTS=OFF
        -DQT_BUILD_BENCHMARKS=OFF
        -DQT_FORCE_BUILD_TOOLS=ON
        -DQT_USE_BUNDLED_BundledFreetype=OFF
        -DQT_USE_BUNDLED_BundledHarfbuzz=OFF
        -DQT_USE_BUNDLED_BundledLibpng=OFF
        -DQT_USE_BUNDLED_BundledPcre2=OFF
        -DQT_USE_BUNDLED_BundledZLIB=OFF
        -DFEATURE_relocatable=ON
        -DHOST_PERL=${PERL}
        ${FEATURE_OPTIONS}
        ${INPUT_OPTIONS}
        ${PLATFORM_OPTIONS}
        ${DISABLE_OPTIONS}
)

vcpkg_cmake_install()

# Install Qt6BuildInternals cmake infrastructure
# Qt doesn't install these by default - they're needed for building Qt submodules like qtsvg
# We copy the full cmake infrastructure from the source tree
set(_bi_dest "${CURRENT_PACKAGES_DIR}/share/Qt6BuildInternals")
file(MAKE_DIRECTORY "${_bi_dest}")

# Copy the entire cmake directory from source (needed for Qt build infrastructure)
set(_cmake_dest "${CURRENT_PACKAGES_DIR}/share/Qt6")
file(MAKE_DIRECTORY "${_cmake_dest}")
file(COPY "${SOURCE_PATH}/cmake/" DESTINATION "${_cmake_dest}")

# Create Qt6BuildInternalsConfig.cmake that sets up the environment and includes Qt's cmake modules
# Note: Using string() to substitute QT_VERSION since bracket strings [=[ ]=] don't expand variables
set(_bi_config_content [=[
# Qt6BuildInternals CMake package configuration file
# Auto-generated by vcpkg qtbase portfile for building Qt submodules

cmake_minimum_required(VERSION 3.16)

# Version info for find_package
set(PACKAGE_VERSION "@QT_VERSION@")

# Set up required variables
get_filename_component(_qt6_share_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(QT_BUILD_INTERNALS_PATH "${CMAKE_CURRENT_LIST_DIR}")
set(QT_CMAKE_EXPORT_NAMESPACE "Qt6")
set(INSTALL_CMAKE_NAMESPACE "Qt6")

# Point to the Qt cmake modules directory (copied from source)
set(QT_CMAKE_DIR "${_qt6_share_dir}")

# Add Qt cmake modules to CMAKE_MODULE_PATH
list(PREPEND CMAKE_MODULE_PATH "${_qt6_share_dir}")
list(PREPEND CMAKE_MODULE_PATH "${_qt6_share_dir}/QtBuildInternals")
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")

# Set required Qt build variables
set(QT_WILL_INSTALL TRUE)
set(QT_BUILDING_QT TRUE)

# Include the QtBuildInternals configuration from source
if(EXISTS "${_qt6_share_dir}/QtBuildInternals/QtBuildInternalsConfig.cmake")
    # Prevent infinite recursion - use the source config directly
    set(_qt_bi_src_config "${_qt6_share_dir}/QtBuildInternals/QtBuildInternalsConfig.cmake")
    include("${_qt_bi_src_config}")
endif()

# Set the package as found
set(Qt6BuildInternals_FOUND TRUE)
set(Qt6BuildInternals_VERSION "@QT_VERSION@")
]=])
string(REPLACE "@QT_VERSION@" "${QT_VERSION}" _bi_config_content "${_bi_config_content}")
file(WRITE "${_bi_dest}/Qt6BuildInternalsConfig.cmake" "${_bi_config_content}")

# Create Qt6BuildInternalsConfigVersion.cmake for cmake find_package version checking
set(_bi_version_content [=[
# Qt6BuildInternals version file for CMake find_package
set(PACKAGE_VERSION "@QT_VERSION@")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
]=])
string(REPLACE "@QT_VERSION@" "${QT_VERSION}" _bi_version_content "${_bi_version_content}")
file(WRITE "${_bi_dest}/Qt6BuildInternalsConfigVersion.cmake" "${_bi_version_content}")

# Fix up Qt6 cmake config directories
# Qt6 installs ALL cmake configs into lib/cmake/Qt6/ (flat structure)
# But Qt6Config.cmake expects components in separate directories like share/Qt6Core/
# We need to fix up Qt6 first, then create the component directories

# First, fix up the main Qt6 directory
vcpkg_cmake_config_fixup(PACKAGE_NAME "Qt6" CONFIG_PATH "lib/cmake/Qt6")

# Qt6 component modules - these need their own directories under share/
# Include both library components and their Tools packages (moc/rcc/uic)
set(_qt6_components
    Qt6Core
    Qt6CoreTools
    Qt6Gui
    Qt6GuiTools
    Qt6Widgets
    Qt6WidgetsTools
    Qt6OpenGL
    Qt6OpenGLWidgets
    Qt6Concurrent
    Qt6Xml
)

# Create component directories with wrapper configs that forward to share/Qt6/
foreach(_comp IN LISTS _qt6_components)
    set(_comp_dir "${CURRENT_PACKAGES_DIR}/share/${_comp}")
    file(MAKE_DIRECTORY "${_comp_dir}")

    # Create a wrapper config that includes the original from share/Qt6/
    file(WRITE "${_comp_dir}/${_comp}Config.cmake"
"# Wrapper config for ${_comp} - forwards to share/Qt6/${_comp}Config.cmake
get_filename_component(_qt6_root \"\${CMAKE_CURRENT_LIST_DIR}/..\" ABSOLUTE)
include(\"\${_qt6_root}/Qt6/${_comp}Config.cmake\")
")

    # Create a ConfigVersion file for the component
    file(WRITE "${_comp_dir}/${_comp}ConfigVersion.cmake"
"set(PACKAGE_VERSION \"${QT_VERSION}\")
set(PACKAGE_VERSION_COMPATIBLE TRUE)
if(\"\${PACKAGE_FIND_VERSION}\" STREQUAL \"${QT_VERSION}\")
    set(PACKAGE_VERSION_EXACT TRUE)
endif()
")
endforeach()

vcpkg_copy_pdbs()

# Copy tools (only for shared builds - static builds don't produce tools)
if(NOT VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    set(QT_TOOLS moc rcc uic)
    vcpkg_copy_tools(TOOL_NAMES ${QT_TOOLS} SEARCH_DIR "${CURRENT_PACKAGES_DIR}/bin" AUTO_CLEAN)
endif()

# Clean up
file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/lib/cmake"
    "${CURRENT_PACKAGES_DIR}/debug/share"
    "${CURRENT_PACKAGES_DIR}/lib/cmake"
)

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

# Install license
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSES/LGPL-3.0-only.txt")
